opentibiabr/myaac

- login.php
Added and improved login file to myaac.
(tested ok)
> feat: addition and improvement of login.php

- system/pages/createcharacterauction.php
- system/pages/currentcharactertrades.php
Fixed some places where sql injection was possible.
> fix: char bazaar sql injection

- .gitignore
- common.php
- config.php
- index.php
- login.php
- system/libs/CreateCharacter.php
- system/libs/pot/OTS_Player.php
- system/migrate.php
- system/migrations/33.php
- system/pages/account/change_main.php
- system/templates/account.change_comment.html.twig
- system/templates/account.change_main.html.twig
- system/templates/online.html.twig
- templates/tibiacom/account.management.html.twig
- templates/tibiacom/buttons.change_main.html.twig
Created change main character functionality and adjusted in login.php.
before:
After:
(validation of coins in account)
Tested OK.
> feature: create main character in account

- install/includes/schema.sql
Adjusted schema.sql to add ismain column in players table.
> fix: add ismain column in the players table

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/request.yaml
> fix: improve github templates.

- admin/pages/accounts.php
- admin/pages/modules/templates/points.html.twig
- login.php
- system/functions.php
- system/libs/pot/OTS_Account.php
- system/libs/pot/OTS_Row_DAO.php
- system/pages/account/change_info.php
- system/pages/accountmanagement.php
- system/pages/characters.php
- system/templates/account.management.html.twig
- system/templates/admin.dashboard.html.twig
- system/templates/characters.html.twig
- system/templates/exception.html.twig
- templates/tibiacom/account.management.html.twig
- templates/tibiacom/boxes/premium.php
- templates/tibiacom/index.php
> feat: vip system improves

- admin/index.php
- admin/pages/premiumvipupdater.php
- admin/template/template.php
- login.php
Created a migration that fixes premdays and lastday of accounts
> fix: premdays and lastday updater

- README.md
- common.php
- install/includes/schema.sql
> feat: updated info and configs.

- install/includes/schema.sql
- install/tools/5-database.php
Fixed install, moved columns `phone` and `ismain` from schema.sql to 5-database.php
> fix: column phone and ismain in database install

- config.php
- system/pages/account/change_info.php
- system/pages/account/register.php
- system/pages/account/register_new.php
- system/pages/accountmanagement.php
- system/templates/account.change_info.html.twig
- system/templates/account.generate_recovery_key.html.twig
- templates/tibiacom/account.management.html.twig
Created config and functionality to update the info when registering an account.
|with config activated |
| ------------- |
|![image](https://github.com/opentibiabr/myaac/assets/7812282/19ac71d9-8b86-4098-84f8-f7644f3e5b37) |
|![image](https://github.com/opentibiabr/myaac/assets/7812282/e7de7bbc-6de2-4476-88f7-e321e4b44b9a) |
|![image](https://github.com/opentibiabr/myaac/assets/7812282/692d150b-a370-4807-ba84-073ab12cd68c) |
|![image](https://github.com/opentibiabr/myaac/assets/7812282/1d0d3e23-e1f4-4cf3-bf3f-e319792f36e3) |
| ![image](https://github.com/opentibiabr/myaac/assets/7812282/4b55a507-b381-4cb3-80fd-83869ecd55a3) |
> feat: improvement of account register and recovery key

- templates/tibiacom/index.php
> fix: background size

- templates/tibiacom/boxes/rank.php
> fix: rank margin top

- config.php
- templates/tibiacom/boxes/serversave.php
> fix: server save countdown

- templates/tibiacom/index.php
> fix: boosted boss looktypeEx

- config.php
- system/pages/createaccount.php
- system/templates/account.welcome_mail.html.twig
Config and function to show email and password in welcome mail.
> feat: show email and password in welcome mail

- config.php
- system/functions.php
- system/init.php
- system/pages/serverinfo.php
- system/templates/serverinfo.html.twig
- templates/tibiacom/boxes/serversave.php
Improvement in server info page. Created list of rates from stages.lua.
Co-author: @LeoTKBR 
rates off:
rates on:
> improve: server info page

- admin/pages/fixvippremiumnewsystem.php
- admin/pages/premiumvipupdater.php
- admin/template/template.php
VIP Updater: created a new admin function to add vip/premium days to all accounts. moved the older to 'fixvippremiumnewsystem.php'
**Test Configuration**:
- MyAAC Version: (latest: 0.8.12)
- Browser: Chrome
- Operating System: Windows 11
> feat: vip or premium add days

- admin/pages/modifiers.php
Created a new button for reset coins transferable and adjusted others.
> fix: menu modifiers

- admin/pages/modules/templates/coins.html.twig
- admin/pages/modules/templates/coinstransferable.html.twig
- admin/pages/modules/templates/lastlogin.html.twig
- system/templates/admin.dashboard.html.twig
- system/templates/admin.statistics.html.twig
Adjusted columns size of boxes in dash.
> improve: dashboard boxes

- system/pages/lostaccount.php
- system/pages/lostaccount/step1.php
- system/pages/lostaccount/step2.php
- system/pages/lostaccount/step3.php
- system/templates/account.lost.form.html.twig
Now, players can recover their account, without characters created.
**Test Configuration**:
- MyAAC Version: (latest: 0.8.15)
- Browser: Chrome
- Operating System: Windows / Ubuntu
> feat: lost account improvement

- admin/pages/dashboard.php
- admin/pages/pag_transactions.php
- system/templates/admin.statistics.html.twig
Created checks to table 'pagseguro_transactions'
> fix: pagseguro validations

- admin/pages/accounts.php
> fix: search account by number

- common.php
- index.php
- system/status.php
- system/templates/serverinfo.html.twig
- Updated uptime on serverinfo page. 
- Added check on 'Level to create guild'.
> improvement: serverinfo page

- system/templates/forum.show_thread.html.twig
Fix player name in forum post.
**Test Configuration**:
- MyAAC Version: (latest: 0.8.16)
- Browser:
- Operating System:
> fix: player name in forum post

- system/pages/forum/new_post.php
Fix XSS in forum.
Thanks [rafaelcintralopes](https://github.com/rafaelcintralopes) for the report.
**Test Configuration**:
- MyAAC Version: (latest: 0.8.16)
- Browser:
- Operating System:
> fix: XSS in forum
